### ISSUE TITLE
Sidebar disappears when scrolling in the latest version of Chrome

### ISSUE THREAD

**Issue by francesca-gaunard-cko** [Redocly/redoc#1167]
Since updating Chrome this morning, I'm experiencing issues with the sidebar. If I scroll down a page using ReDoc, the sidebar is no longer sticky. It eventually just disappears.  

<img width="1439" alt="Screenshot 2020-02-06 at 11 51 52" src="https://user-images.githubusercontent.com/43998723/73934827-27bba980-48d7-11ea-82fa-6f92207f4194.png">

I'm running version Version 80.0.3987.87 of Chrome on Mac OS X.  I checked in Incognito mode and was able to reproduce the same behaviour.

**Comment by ErlendSB** [comment]
I'm experiencing the same.
One interesting observation is that the live demo (http://redocly.github.io/redoc/) works as expected. 
The main difference is the top navbar, so maybe this can help is some way.

**Comment by philib** [comment]
We have the same problem with our [documentation](https://api.eu.meisterplan.com).
Is there any workaround?

**Comment by abjsyn** [comment]
> We have the same problem with our [documentation](https://api.eu.meisterplan.com).
> Is there any workaround?

Check on Firefox 72.0.2 (64 bit), seems to bee ok.

**Comment by hvnon** [comment]
So am i. 
We're got the same with Chrome 80.+.
Edge chromium 79.+ is working fine

**Comment by itd-sk** [comment]
This issue has a pretty high impact for us because right now the documentation is de facto not usable  with Chrome. Please let me know if we can support you to fix this issue. Thanks in advance.

**Comment by RomanHotsiy** [comment]
Hey guys. Sorry for the huge delay. I've been traveling for the last week. I will check this issue ASAP.

Anyone has any clue why this happens?

**Comment by RomanHotsiy** [comment]
Should be fixed on v2.0.0-rc.23 :tada:

**Comment by eriolo** [comment]
> Should be fixed on v2.0.0-rc.23 🎉

When using `https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.23/bundles/redoc.standalone.js"` locally the problem still persists.

**Comment by RomanHotsiy** [comment]
@eriolo your link is to alpha.23 not rc.23, correct link:

https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.23/bundles/redoc.standalone.js
