### ISSUE TITLE
How to use theme with standalone tag

### ISSUE THREAD

**Issue by bbusch19** [Redocly/redoc#1248]
Hi, I am currently using the redoc tag in a Vuejs project. How can I get themes to work with the tag? Do I need to pass it as an Object? A string?

Here is an example:

```html
<redoc
      :theme="{
        colors: {
          rightPanel: { backgroundColor: '#DFC350', textColor: '#445AFF' },
          http: {
            get: '#DFC350'
          }
        }
      }"
      spec-url="http://petstore.swagger.io/v2/swagger.json"
    />
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js" />
```

Any help would be much appreciated. Thanks!

**Comment by RomanHotsiy** [comment]
Redoc tag is a regular html tag. It is not web-component. When Redoc js loads it binds to this tag. So you can pass only string via attributes. You can pass the theme as a JSON string:

```
<redoc
  theme="{colors: {rightPanel: { backgroundColor: '#DFC350', textColor: '#445AFF' }, http: { get: '#DFC350' }}}"
  spec-url="http://petstore.swagger.io/v2/swagger.json"
/>
```

Alternatively, you can init Redoc manually using `Redoc.init`, see https://github.com/Redocly/redoc#advanced-usage-of-standalone-version

**Comment by wjdp** [comment]
@RomanHotsiy setting theme on the standalone tag seems doesn't seem to work. Using your example:

```
<!DOCTYPE html>
<html>
  <head>
    <title>ReDoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <!--
    ReDoc doesn't change outer page styles
    -->
    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='petstore.yaml' disable-search="true" theme="{colors: {rightPanel: { backgroundColor: '#FF0000', textColor: '#445AFF' }, http: { get: '#DFC350' }}}"></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/1690934/85030469-64e15380-b175-11ea-87f1-4c62426374e8.png)

I've checked `theme.ts`, it seems `rightPanel` has moved to the root of the object. Just trying to target this key also does nothing.

![image](https://user-images.githubusercontent.com/1690934/85030701-b093fd00-b175-11ea-8451-b006963367c5.png)

Note I have included `disable-search` and that does function.

**Comment by RomanHotsiy** [comment]
Oh, my bad, try passing it as a valid json string (not js), use double-quotes.

`{"colors": {"rightPanel": { "backgroundColor": "#FF0000"...`

**Comment by mknaw** [comment]
Also having no luck, even with the JSON string. Looking at the source, I'm not sure how it would work - it doesn't looked like the theme is parsed before it gets passed to `RedocNormalizedOptions`, so the `{ ...raw.theme, ...}` passed to `mergeOptions` seems to just destructure the string?

**Comment by RomanHotsiy** [comment]
@mknaw yes, looks like you are right. I will fix that.

**Comment by tjperry07** [comment]
Just bumping this since the theme is holding me back from being able to use it.

**Comment by ZeProf2Code** [comment]
bump

**Comment by AlexRoodo** [comment]
bump

**Comment by Shahaed** [comment]
Since still broken on this redoc version, this guy forked the code to make it work: https://github.com/langhabel/redoc.

His simple commit is a few lines above: `fix: parse json theme string for standalone tag`

**Comment by RomanHotsiy** [comment]
Fixed in https://github.com/Redocly/redoc/pull/1492

The new version will be published later this week. Thanks for bumping everyone 🙌 !

**Comment by hheavener-kyd** [comment]
This is still not working on my end. I cannot change the sidebar color no matter what I do. I've even tried overriding the CSS rules but I can't figure out where the sidebar color is even coming from so that's a dead end. Is anyone else still experiencing issues with this using the standalone version?

**Comment by AiyionPrime** [comment]
@hheavener-kyd Accoding to https://github.com/Redocly/redoc/pull/1491/files#diff-3b0d0fd534132dcc7f29e23eacce87bb8960ef97b849de3616fab48113f017dfR25 Its working like this:

`theme='{"colors": {"primary": { "main": "#DFC350"}}, "rightPanel": { "backgroundColor": "#DFC350", "textColor": "#445AFF", "http": {"get": "#DFC350"}}}'`
