### ISSUE TITLE
Doesn't really work well with nativeScrollbars

### ISSUE THREAD

**Issue by benwiley4000** [Redocly/redoc#1278]
I tried setting `nativeScrollbars: true` for my docs (using the `RedocStandalone` React component), mostly based on the fact that the option was set in the React usage example, not for any other reason... and the scrolling is sort of unusable.

When I try to scroll down the list of API sections they start auto-opening which means I can never actually scroll to the bottom, and it's also not totally obvious it's a scrolling view until you start scrolling (at least in macOS which doesn't show the scrollbar until you begin scrolling).

All that is to say that I removed the nativeScrollbars option from my config and everything works great now. So maybe that config should be less prominently suggested in the docs until it begins working a bit more smoothly.

**Comment by RomanHotsiy** [comment]
Could you share a short screencast, I believe it may be related to the context you use RedocStandalone in.

**Comment by McFlat** [comment]
jumpy when scrolling through api docs https://docs.joinpeertube.org/api-rest-reference.html

**Comment by RomanHotsiy** [comment]
@McFlat you use a broken release `"2.0.0-rc.8-1"`

Use the latest `rc.30`, this bug is already fixed.

**Comment by petersamokhin** [comment]
`"redoc": "^2.0.0-rc.48"` and seems like it's still not fixed
