### ISSUE TITLE
Request/Response Schema incorrectly renders as 'any'

### ISSUE THREAD

**Issue by msrd0** [Redocly/redoc#1608]
This bug only happens when inlining the specification into the JavaScript delivered to the Browser. Using an HTTP url delivering the exact same content does not trigger this bug.

## Incorrect Behaviour

![image](https://user-images.githubusercontent.com/7853372/117558154-3492f400-b06a-11eb-8c15-f188bf6e8637.png)

## Expected Behaviour

![image](https://user-images.githubusercontent.com/7853372/117558161-42487980-b06a-11eb-88c5-faab7c8bf124.png)

## Steps to Reproduce

Copy this to a file and open it in your browser: https://gist.github.com/msrd0/136714f9ca0a161e359cf35854b78a53

Redoc version: 2.0.0-rc.53

**Comment by RomanHotsiy** [comment]
@msrd0 was it resolved?

**Comment by msrd0** [comment]
Well, I don't know how it was resolved but it doesn't happen anymore. I guess I have to blame it on me not knowing javascript well enough.

**Comment by RomanHotsiy** [comment]
Thanks for the update!

**Comment by roni-frantchi** [comment]
Hey @RomanHotsiy I'm still getting it - 
Using the latest Redoc CLI:  
```
➜ npx redoc-cli --version         
0.12.3
```
Given [this schema](https://gist.github.com/roni-frantchi/554d1c90e884c0a9112c8ad0f84984e6)
It produced [this html](https://gist.github.com/roni-frantchi/75c693df6a05a7dbced8d62a9a3535f2)

You can see the issue in `#operation/updateBlueprint` for instance
