### ISSUE TITLE
False positive recursion detection from version 2.0.0-alpha.13

### ISSUE THREAD

**Issue by misos1** [Redocly/redoc#695]
From version 2.0.0-alpha.13 is broken recursion detection as it detects recursion where is no recursion. Things worsened from 2.0.0-alpha.29 up to latest version.

<details><summary>Reduced test case (click)</summary>

``` yaml
openapi: 3.0.0
info:
  version: 1.2.3
  title: api

paths:
  /api:
    post:
      summary: api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
      responses:
        200:
          description: Ok

components:
  schemas:
    D:
      type: object
      properties:
        d:
          type: string
    
    C:
      type: object
      properties:
        type:
          type: string
        c:
          allOf:
            - $ref: '#/components/schemas/D'
    
    B1:
      allOf:
        - $ref: '#/components/schemas/C'
      type: object
      properties:
        b1:
          type: string

    B2:
      allOf:
        - $ref: '#/components/schemas/C'
      type: object
      properties:
        b2:
          type: string
        

    A1:
      allOf:
        - $ref: '#/components/schemas/C'
        - $ref: '#/components/schemas/B1'
      type: object
      properties:
        a1:
          type: string


    A2:
      allOf:
        - $ref: '#/components/schemas/C'
        - $ref: '#/components/schemas/B2'
      type: object
      properties:
        a2:
          type: string

    Abc:
      type: array
      items:
        oneOf:
          - $ref: '#/components/schemas/A1'
          - $ref: '#/components/schemas/A2'
        discriminator:
          propertyName: type
          mapping:
            a1: '#/components/schemas/A1'
            a2: '#/components/schemas/A2'

    Data:
      allOf:
        - type: object
          properties:
            abc:
              allOf:
                - $ref: '#/components/schemas/Abc'
```

</details>
<br/>

With versions from 2.0.0-alpha.29 to 2.0.0-alpha.41 it looks like this:
<img width="478" alt="screen shot 2018-10-31 at 21 37 53" src="https://user-images.githubusercontent.com/30872003/47817160-4090f300-dd55-11e8-84b8-fc67b90ab159.png">

Versions from 2.0.0-alpha.13 to 2.0.0-alpha.28:
<img width="485" alt="screen shot 2018-10-31 at 21 39 39" src="https://user-images.githubusercontent.com/30872003/47817256-7e8e1700-dd55-11e8-98f8-b44ba45db7ab.png">

How it should look correctly (2.0.0-alpha.12):
<img width="484" alt="screen shot 2018-10-31 at 21 40 26" src="https://user-images.githubusercontent.com/30872003/47817323-99608b80-dd55-11e8-9e20-648dfb2ab875.png">

There is no recursion here is graph of objects, it is simple linear flow:
<img width="503" alt="screen shot 2018-10-31 at 22 00 58" src="https://user-images.githubusercontent.com/30872003/47818568-7daab480-dd58-11e8-8972-ff3427fb4480.png">

<details>

``` mermaid
graph LR;
    Data-->Abc;
    Abc-->A1;
    Abc-->A2;
    A1-->C;
    A1-->B1;
    A2-->C;
    A2-->B2;
    B1-->C;
    B2-->C;
    C-->D;
```

</details>

**Comment by RomanGotsiy** [comment]
Thanks for the super detailed issue report 👍 !

I am aware of this issue and I think I have a fix locally.
Still testing it.

**Comment by migmit-kinja** [comment]
Any news on that? We're experiencing a similar issue.

**Comment by pmogren** [comment]
I am also encountering false recursion detection in redoc. It works correctly in Swagger-UI.

**Comment by RomanHotsiy** [comment]
Should be fixed by faa74d60

Will be available in the new release.

**Comment by misos1** [comment]
Seems this fix is already published because when I tested original example it showed no recursion.

But I am afraid I found counterexample:

``` yaml
openapi: 3.0.0
info:
  version: 1.2.3
  title: api

paths:
  /api:
    post:
      summary: api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Data'
      responses:
        200:
          description: Ok

components:
  schemas:
    B:
      type: object
      properties:
        b:
          type: string
    A1:
      type: object
      properties:
        a:
          type: array
          items:
            $ref: '#/components/schemas/B'
    A2:
      type: object
      properties:
        a:
          type: array
          items:
            $ref: '#/components/schemas/B'
    Data:
      allOf:
        - $ref: '#/components/schemas/A1'
        - $ref: '#/components/schemas/A2'
```

With https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js

<img width="307" alt="Screenshot 2019-10-01 at 21 15 57" src="https://user-images.githubusercontent.com/30872003/65993059-b8e5c400-e490-11e9-8f35-c6614012d87d.png">

With https://unpkg.com/redoc@2.0.0-alpha.12/bundles/redoc.standalone.js

<img width="307" alt="Screenshot 2019-10-01 at 21 16 16" src="https://user-images.githubusercontent.com/30872003/65993099-cbf89400-e490-11e9-81ec-161c18bf20b0.png">

Seems something does not propagate well through arrays.

Also why was alpha 12 without such issues? I see that also there is recursion detection and seems it works well when I intentionally create some recursion and seems it has no false positives.

**Comment by sergburn** [comment]
Yes, it still fails with 2.0.0-rc.23, regardless whether common model is reused within array or as a single-value property.

Another code example
```
openapi: 3.0.0

info:
  title: Test spec
  description: Test spec for ReDoc bug
  version: v1

paths:
  /distro:
    post:
      requestBody:
        $ref: "#/components/requestBodies/Distro"
      responses:
        200:
          description: Success
          content:
            application/json:
              example: { "message": "ok" }

components:
  schemas:

    Version:
      properties:
        major:
          type: integer
        minor:
          type: integer

    Library:
      allOf:
        - properties:
            name:
              type: string
        - $ref: "#/components/schemas/Version"

    App:
      properties:
        name:
          type: string
        dependencies:
          type: array
          items:      # rendered as recursive
            $ref: "#/components/schemas/Library"
        executable:   # rendered as recursive
            $ref: "#/components/schemas/Library"

    Bundle:
      allOf:
        - $ref: "#/components/schemas/Version"
        - $ref: "#/components/schemas/App"

  requestBodies:
    Distro:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Bundle"
```
