### ISSUE TITLE
Regression: Double slashes added to full URL display

### ISSUE THREAD

**Issue by mramato** [Redocly/redoc#912]
Attempted to upgrade to `redoc@2.0.0-rc.8-1` this morning and noticed that it is inserting double slashes in the full url for a route:

![image](https://user-images.githubusercontent.com/1495196/57636868-0b712300-7578-11e9-9e82-48907e0575c0.png)

Minimal reproduction.

```yaml
openapi: 3.0.2

info:
  title: Double Slash
  version: v1
servers:
  - url: https://api.test.invalid

paths:
  /v1:
    get:
      summary: Double slash bug
      responses:
        200:
          description: OK
```

**Comment by EspressoBeans** [comment]
This also broke our documentation examples as well.  @mramato, what is your current work around?  I'm using NSwag which brings in https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js.  And when I look at the js in the link it shows Version: "2.0.0-rc.7", so maybe both versions are affected, or js comments are not updated.  (??)

**Comment by RomanGotsiy** [comment]
Hey @mramato.

Are you sure you are running `redoc@2.0.0-rc.8-1`? You can check the comment block on the top of the file or run in console: `Redoc.version`

I can't reproduce the issue on the latest version. I can reproduce using `2.0.0-rc.7` though. @EspressoBeans it must be jsdelivr cache. It should get propagated to the latest version within next 24 hours.

**Comment by RomanGotsiy** [comment]
There indeed was a minor regression and I just fixed it.
But @mramato, your example works fine for me on `rc.8-1`.

Will release a new version closer to the end of the week.

**Comment by mramato** [comment]
@RomanGotsiy I was using the CDN:

```
<script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.8-1/bundles/redoc.standalone.js"> </script>
```

And `Redoc.version` is `"2.0.0-rc.8-1"`

**Comment by EspressoBeans** [comment]
My api redoc page is automatically bringing in `https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js` and the version within the js file is: 
```
/*!
 * ReDoc - OpenAPI/Swagger-generated API Reference Documentation
 * -------------------------------------------------------------
 *   Version: "2.0.0-rc.8-1"
 *   Repo: https://github.com/Rebilly/ReDoc
 */
```
I'm still experiencing the extra slash at the end of the host server.  Is there any information I can give you to help you fix?

**Comment by RomanGotsiy** [comment]
@EspressoBeans could you share your spec servers? Do you use OpenAPI 3 or OpenAPI 2?

Ideally would be great if you can just share the link to your docs.

Thanks!

**Comment by EspressoBeans** [comment]
Unfortunately I cannot share a link to my docs because they are still internal links (not public), however here is the top section of my spec document.  It shows that I'm using OpenAPI 3 and shows my server URL:

```
{
  "x-generator": "NSwag v12.2.5.0 (NJsonSchema v9.13.37.0 (Newtonsoft.Json v12.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "Warehouse API",
    "description": "This API is for interfacing with Crane warehouse data for consumption into reports, data processing, and web applications.\n\n___\n# Versioning\nAPI released versions are summarized below:\n\nAPI version | Changes\n-------------| ---------\n1.3 | Added inventory available quantity across all warehouses.\n1.2 | Added inventory available quantity for single material.\n1.1 | Updated endpoint routing convention.\n1.0 | Initial version for material details.\n\n\n___\n# Errors\nThe API uses standard HTTP status codes to indicate the success or failure of the API call. The body of an error response will be JSON in the following format:\n\n```\n{\n  \"apiErrorMessage\": \"The requested shipment does not exist\"\n}\n```\n\n\n___\n",
    "version": "v1.4",
    "x-logo": {
      "url": "https://mc1.airscorp.com/portal-upload/RMPOD1WebDocument/2019/2/clientdata_1024732/20/1655/d424c4f2-38c2-4eaa-bb4f-6862197bf467.jpg",
      "altText": "Logo",
      "href": "https://craneww.com/"
    }
  },
  "servers": [
    {
      "url": "https://xxxx.api.craneww.com:12443"
    }
  ],
```

**Comment by EspressoBeans** [comment]
![image](https://user-images.githubusercontent.com/17069446/57708257-a4fb0c00-762e-11e9-8672-bc6f5ec0c51d.png)

**Comment by EspressoBeans** [comment]
i have confirmed that https://github.com/Rebilly/ReDoc/tree/v2.0.0-alpha.41 version does not have the problem.

**Comment by darklynx** [comment]
I can see double-slash after server with my OpenAPI ver. 2: https://raw.githubusercontent.com/darklynx/request-baskets/master/doc/api-swagger.yaml

It has `basePath: /` hence doubles the // when it is combined with paths

Hopefully its fixed with `v2.0.0-alpha.41`, thanks!

**Comment by mramato** [comment]
> Will release a new version closer to the end of the week.

Is a new release still planned anytime soon?  I would love to update to the latest version for IE11 fixes but this issue is blocking us.

**Comment by MattFenner** [comment]
I also would like an update on when the new release is please. This is currently affecting our production documentation and would like to know if we should wait for the release or roll back to an older version.

Thanks

**Comment by rlee89** [comment]
Any updates would be greatly appreciated. I'd also like to know if a new release is planned soon.

Thanks!

**Comment by RomanHotsiy** [comment]
A new release is coming in 2-3 days max.

**Comment by pinchukdiana** [comment]
> A new release is coming in 2-3 days max.

Hello @RomanHotsiy are there any updates about the possible release date?
Thanks

**Comment by RomanHotsiy** [comment]
The latest version has been released already: v2.0.0-rc.10.

Could somebody try and verify if the issue is fixed? Thanks!

**Comment by bkhablenko** [comment]
@RomanHotsiy I tried the new version a moment ago, and the issue seems to have been fixed :tada:

**Comment by rlee89** [comment]
> The latest version has been released already: v2.0.0-rc.10.
> 
> Could somebody try and verify if the issue is fixed? Thanks!

Can also confirm v2.0.0-rc.10 fixes this issue, woo! I think the only thing remaining is to bump the latest tag in the redoc npm package. I'm still seeing `latest` pointed to v2.0.0-rc.8-1, but I do see `redoc-cli` npm package bumped up to 0.8.5 with the dependency to v2.0.0-rc.10. 

Thanks again, really appreciate it!

**Comment by darklynx** [comment]
Latest version (`2.0.0-rc.10`) problem is fixed: https://rbaskets.in/api.html
Thank you very much!
